eureka:
  client:
    service-url:
      defaultZone: http://eureka-server.evergreen.snow:8080/eureka/
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.cloud.client.ip-address}:${server.port}

spring:
  application:
    name: aws-empty-project1

  datasource:
    url: jdbc:mysql://database-1.c1eeu604q8hf.us-east-1.rds.amazonaws.com:3306/sample_db?useSSL=false&allowPublicKeyRetrieval=true
    username: admin
    password: Manikanta
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
    # properties:
    #   hibernate.format_sql: true

  hikari:
    maximum-pool-size: 10
    minimum-idle: 5
    idle-timeout: 30000
    connection-timeout: 20000
    max-lifetime: 1800000

server:
  port: 8080


