server:
  port: 8080

spring:
  application:
    name: landscaping-api-gateway

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lowerCaseServiceId: true
      routes:
        - id: aws-empty-project1
          uri: lb://aws-empty-project1
          predicates:
            - Path=/api/auth/**
eureka:
  client:
    service-url:
      defaultZone: http://eureka-server.evergreen.snow:8080/eureka/
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.cloud.client.ip-address}:${server.port}

auth-service-url: http://54.92.181.186:9093