server:
  port: 8080
  address: 0.0.0.0

spring:
  application:
    name: landscaping-api-gateway

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lowerCaseServiceId: true
      routes:
        - id: aws-empty-project1
          uri: lb://AWS-EMPTY-PROJECT1
          predicates:
            - Path=/api/auth/**
eureka:
  client:
    service-url:
      defaultZone: http://eureka-server.evergreen.snow:8080/eureka/

auth-service-url: http://54.92.181.186:9093